version: '3.8'

services:
  rsa-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=development

  rsa-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
